routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\UserAccountController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\ProblemController;
use App\Http\Controllers\StudentProfileController;
use App\Http\Controllers\ProblemDashboardController;
use App\Http\Controllers\CouncelingController;
use App\Http\Controllers\NewsAndUpdateController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\AccountForumController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [UserController::class, 'landing'])->name('home');


Route::get('/login', function () {
    return view('Auth.index');
})->name('login');

Route::get('/activities', function () {
    return view('Landing.activities');
})->name('activities');

Route::get('/visionMission', function () {
    return view('Landing.visionMission');
})->name('visionMission');

Route::get('/newsupdates', function () {
    return view('Landing.newsupdates');
})->name('newsupdates');

Route::get('/strands', function () {
    return view('Landing.strands');
})->name('strands');

Route::get('/Organization', function () {
    return view('Landing.Organization');
})->name('Organization');

Route::get('/aboutus', function () {
    return view('Landing.aboutus');
})->name('aboutus');

Route::get('/registration', function () {
    return view('Auth.register');
})->name('registration');


Route::get('/forget-password', function () {
    return view('Auth.forgetPassword');
})->name('forget_password');

//sample for reset password
Route::get('/reset-password/{user_id?}', function () {
    return view('Auth.ResetPassword');
})->name('reset-password');

//Authentications/Login
Route::group(['prefix'=> 'auth', 'as' => 'auth.'], function(){
	// For Login
	Route::controller(AuthController::class)->group(function () {
 		 Route::post('request', 'authenticate')->name('authenticate');
 		 Route::get('forget-password-send', 'forgetPassword')->name('forget_password_send');
 		 Route::post('reset-password-send', 'resetPassword')->name('reset_password_send');
	});
});


Route::controller(UserController::class)->group(function(){
	Route::group(['prefix'=> 'users', 'as' => 'users.'], function(){
		 Route::get('', 'index')->name('index');
		 Route::get('list', 'list')->name('list');
		 Route::get('find/{user_id}', 'find')->name('find');
		 Route::post('add', 'add')->name('add');
		 Route::delete('delete/{user_id}', 'trash')->name('delete');
	});
});

Route::group(['middleware' => ['auth']], function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    // staff management
    Route::controller(StaffController::class)->group(function(){
		Route::group(['prefix'=> 'students', 'as' => 'students.'], function(){
			 Route::get('', 'index')->name('index');
			 Route::get('list', 'list')->name('list');
			 Route::get('find/{student_id?}', 'find')->name('find');
			 Route::post('add', 'add')->name('add');
			 Route::delete('delete/{student_id}', 'trash')->name('delete');
		});
	});


    //Students management
	Route::controller(UserAccountController::class)->group(function(){
		Route::group(['prefix'=> 'user_accounts', 'as' => 'user_accounts.'], function(){
			 Route::get('/students', 'index')->name('index');
			 Route::get('list', 'list')->name('list');
			 Route::get('find/{user_id}', 'find')->name('find');
			 Route::post('add', 'add')->name('add');
			 Route::delete('delete/{user_id}', 'trash')->name('delete');
			 Route::get('approve', 'approve')->name('approve');
			 Route::get('disapprove', 'disapprove')->name('disapprove');

		});
	});

	//staff management
	Route::controller(StaffController::class)->group(function(){
		Route::group(['prefix'=> 'staff', 'as' => 'staff.'], function(){
			 Route::get('/students', 'index')->name('index');
			 Route::get('list', 'list')->name('list');
			 Route::get('find/{user_id}', 'find')->name('find');
			 Route::post('add', 'add')->name('add');
			 Route::delete('delete/{user_id}', 'trash')->name('delete');
		});
	});

    Route::get('dashboard', [DashboardController::class, 'index'])->name('index');



});

Route::group(['as' => 'admin.', 'middleware' => ['auth']], function(){
    Route::get('dashboard', [DashboardController::class, 'index'])->name('index');
});


Route::group(['prefix'=> 'account', 'as' => 'account.',  'middleware' => ['auth']], function(){
    Route::get('', [AccountController::class, 'index'])->name('index');
    Route::get('find/{id?}', [AccountController::class, 'find'])->name('find');
    Route::get('edit', [AccountController::class, 'edit'])->name('edit');
});

//problem
Route::group(['prefix' => 'problems', 'as' => 'problems.'], function(){
	Route::controller(ProblemController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::delete('delete/{id?}', 'delete')->name('delete');
	});
});


Route::group(['prefix'=> 'student-profile', 'as' => 'student-profile.',  'middleware' => ['auth']], function(){
    Route::get('', [StudentProfileController::class, 'index'])->name('index');
    Route::get('/change-password', [StudentProfileController::class, 'changePassword'])->name('changePassword');
    Route::get('/change', [StudentProfileController::class, 'change'])->name('change');
    Route::post('/upload', [StudentProfileController::class, 'upload'])->name('upload');
   
});



Route::group(['prefix'=> 'counseling', 'as' => 'counseling.',  'middleware' => ['auth']], function(){
    Route::get('{id?}', [CouncelingController::class, 'index'])->name('index');
});

Route::controller(ProblemDashboardController::class)->group(function(){
	Route::group(['prefix'=> 'problem-dashboard', 'as' => 'problem-dashboard.'], function(){
		 Route::get('', 'index')->name('index');
		 Route::get('active', 'active')->name('active');
		 Route::get('list-active', 'listActive')->name('list_active');
		 Route::get('list', 'list')->name('list');
		 Route::get('find/{id}', 'find')->name('find');
		 Route::post('add', 'add')->name('add');
		 Route::delete('delete/{id}', 'trash')->name('delete');
		 Route::get('approve', 'approve')->name('approve');
		 Route::get('disapprove', 'disapprove')->name('disapprove');
		 Route::get('seen', 'seen')->name('seen');
		 Route::get('list-solve', 'listSolve')->name('list_solve');
		 Route::get('solve', 'solve')->name('solve');
	});
});


Route::controller(NewsAndUpdateController::class)->group(function(){
	Route::group(['prefix'=> 'news_and_update', 'as' => 'news_and_update.'], function(){
		 Route::get('', 'index')->name('index');
    	 Route::get('/activities', [NewsAndUpdateController::class, 'activities'])->name('activities');
    	 Route::get('/news', [NewsAndUpdateController::class, 'news'])->name('news');
	});
});

Route::controller(ForumController::class)->group(function(){
	Route::group(['prefix'=> 'forum', 'as' => 'forum.'], function(){
		 Route::get('/{id?}', 'index')->name('index');
	});
});

Route::get('send', [ForumController::class, 'send'])->name('message.send');
Route::get('list', [ForumController::class, 'list'])->name('forum.list');


Route::controller(AccountForumController::class)->group(function(){
	Route::group(['prefix'=> 'account-forum', 'as' => 'account-forum.'], function(){
		 Route::get('/{id?}', 'index')->name('index');
	});
});

Route::get('account-send', [AccountForumController::class, 'send'])->name('accountMessage.send');
Route::get('account-list', [AccountForumController::class, 'list'])->name('accountForum.list');
Route::get('account-solve', [AccountForumController::class, 'solve'])->name('accountForum.solve');


Route::controller(InboxController::class)->group(function(){
	Route::group(['prefix'=> 'account-inbox', 'as' => 'account-inbox.'], function(){
		 Route::get('', 'index')->name('index');
		 Route::get('/seen-user/{id?}', 'seenUser')->name('seen');
    	
	});
});

app/Models/Problem.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Problem extends Model
{
    use HasFactory;

    protected $fillable = [
        'problem_type',
        'user_id',
        'problem_message',
        'date',
    ];

    public function users(){
        return $this->belongsTo('App\Models\User', 'user_id' , 'user_id');
    }

    public function forums_is_unseen(){
        return $this->hasMany('App\Models\Forum', 'problem_id' , 'id')->whereNull('sender_id')->where('is_seen', 0);
    }

    public function forums_is_notseen(){
        return $this->hasMany('App\Models\Forum', 'problem_id' , 'id')->whereNull('receiver_id')->where('is_seen', 0);
    }
    
}

app/Http/Controllers/ProblemController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Problem;
use Validator;
use Auth;

class ProblemController extends Controller
{
    public function index(){
        return view('Problem.index');
    }

    public function list(){
        $problems = Problem::where('user_id', Auth::user()->user_id)->orderBy('id', 'desc')->get();
        return response()->json(['status' => true, 'data' => $problems]);
    }

    public function save(Request $request, $id = ""){

        if($request->get('problem_type') == 'Other') {
            $validator = Validator::make($request->all(), [
            'problem_type' => 'required',
            'other_option' => 'required',
        ]);
        }else{
            $validator = Validator::make($request->all(), [
            'problem_type' => 'required',
        ]);
        }

        if($validator->fails()){
            return response()->json(['status' => false, 'error' => $validator->errors() ]);
        }else{
            if(!empty($id)){
            if (!empty ($request->get('other_option') )) {
                $problems = Problem::where('id', $id)->update([
                    'problem_type' => $request->get('other_option'),
                ]);
            }else{
                $problems = Problem::where('id', $id)->update([
                    'problem_type' => $request->get('problem_type'),
                ]);
                }
                if($problems){
                    return response()->json(['status' => true, 'message' => 'problems saved successfully!']);
                }
            }else{
                $problems = new Problem;
                $problems->user_id = Auth::user()->user_id;
                $problems->date = now();
            if (!empty ($request->get('other_option') )) {
                $problems->problem_type = $request->get('other_option');
                    
            }else{
                $problems->problem_type = $request->get('problem_type');
                
                }
                  $problems->save();
                  return response()->json(['status' => true, 'message' => 'problems saved successfully!']);


                }
                
            }
        }
    public function find($id){
        $problems = Problem::findOrFail($id);
        return response()->json(['status' => true, 'data' => $problems ]);
    }

    public function delete($id){
        $problems = Problem::findOrFail($id);
        if($problems->delete()){
            return response()->json(['status' => true, 'message' => 'Record deleted successfully!' ]);
        }
    }

}

resources/views/Problem/index.blade.php
@extends('Layout.account.app')
@section('title', 'Counseling')
@section('content')
	<div class="container-fluid pt-3">
	<div class="row mb-3">
		<div class="col-md-6 text-capitalize"><h1>Problems Management</h2></div>
		<div class="col-md-6 text-right"><button type="button" onclick="add_problems();" class="btn btn-primary">Add Problems</button></div>
		<div class="col-md-12">
			<table class="table table-bordered table-striped" id="tbl_problems" style="width: 100%;"></table>
		</div>
	</div>
</div>

<!-- Modal Form -->
<form class="needs-validation" id="problem_form" action="{{ route('problems.save') }}" novalidate>
	<div class="modal fade" tabindex="-1" role="dialog" id="modal_problem_form" data-backdrop="static">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="modal_problem_form_title">Add Problems</h5>
					<button class="close" data-dismiss="modal" onclick="close_modal()">&times;</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<input type="hidden" name="id" id="id" />
						<div class="col-md-12 mb-2 mt-2">
							<label>Problem type</label>
							<select name="problem_type" id="problem_type" class="form-control" onchange="problem_select(this.value)">
								<option value="" selected="" disabled="">Please Select Problem type</option>
								<option value="Family Problem">Family Problem</option>
								<option value="Financial Problem">Financial Problem</option>
								<option value="Academics Problem">Academics Problem</option>
								<option value="Other">Other</option>
							</select>
							<div class="invalid-feedback" id="err_problem_type"></div>
						</div>
						<div class="col-md-12 mb-2 mt-2" id="other_problem_div">
							<label>Other Problem</label>
							<input type="text" name="other_option" id="other_option" class="form-control " required  placeholder="Specify the problem"/>
							<div class="invalid-feedback" id="err_other_option"></div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-success" id="problem_form_btn" >Save</button>
				</div>
			</div>
		</div>
	</div>
</form>
@endsection
@section('script')
<script type="text/javascript">

function problem_select(val){
	if ($('#problem_type').val() == 'Other') {
	$('#other_problem_div').show();

	}else{
	$('#other_problem_div').hide();
	$('#other_option').val('');

	}
}

function add_problems(){
	$("#id").val('');
	$('#problem_type').val('');
	$('#problem_message').val('');
	$('#other_problem_div').hide();
	$("#modal_problem_form").modal('show');
}

var tbl_problems;
show_problems();
function show_problems(){
	if(tbl_problems){
		tbl_problems.destroy();
	}
	tbl_samples = $('#tbl_problems').DataTable({
		destroy: true,
		pageLength: 10,
		responsive: true,
		aaSorting: [],
		ajax: "{{ route('problems.list') }}",
		deferRender: true,
		columns: [
			{
				className: '',
				"data": 'problem_type',
				"title": 'Problem type',
				"orderable": false,
			},
			{
				className: '',
				"data": 'date',
				"title": 'Date',
				"orderable": false,
			},
			{
				className: '',
				"data": 'status',
				"title": 'Status',
				"class": 'text-center',
				"orderable": false,
				"render": function(data, type, row, meta){
		        newdata = '';
		        if (data == 0) {
		        newdata += ' <span class="badge badge-warning mt-1" style="width: 80px" type="button">Pending</i></span>';
		        }else if(data == 1){
		        newdata += ' <span class="badge badge-primary mt-1" style="width: 80px" type="button">Approved</i></span>';
		        }else if(data == 2){
		        newdata += ' <span class="badge badge-danger mt-1" style="width: 80px" type="button">Declined</i></span>';
		        }else{
		        newdata += ' <span class="badge badge-success mt-1" style="width: 80px" type="button">Solved</i></span>';
		        }
		        return newdata;
		    }
			},
			{
				className: 'width-option-1 text-center',
				width: '15%',
				"data": 'id',
				"orderable": false,
				"title": 'Options',
				"render": function(data, type, row, meta){
					newdata = '';
					newdata += '<button class="btn btn-success btn-sm font-base mt-1"  onclick="edit_problems('+row.id+')" type="button"><i class="fa fa-edit"></i></button> ';
					newdata += ' <button class="btn btn-danger btn-sm font-base mt-1" onclick="delete_problems('+row.id+');" type="button"><i class="fa fa-trash"></i></button>';
					return newdata;
				}
			}
		]
	});
}


$("#problem_form").on('submit', function(e){
	e.preventDefault();
	let id = $('#id').val();
	let url = $(this).attr('action');
	let formData = $(this).serialize();
	$.ajax({
		type:"POST",
		url:url+'/'+id,
		data:formData,
		dataType:'json',
		beforeSend:function(){
			
		},
		success:function(response){
			if (response.status == true) {
				swal("Success", response.message, "success");
				show_problems();
				$('#modal_problem_form').modal('hide');
			}else{
				showValidator(response.error,'user_account_form');
				console.log(response);
			}
				validation('problem_form', response.error);
		},
		error: function(error){
			
			console.log(error);
		}
	});
});

function edit_problems(id){
	$.ajax({
		type:"GET",
		url:"{{ route('problems.find') }}/"+id,
		data:{},
		dataType:'json',
		beforeSend:function(){
		},
		success:function(response){
			if (response.status == true) {
				$('#other_problem_div').hide();
				$('#id').val(response.data.id);
				$('#problem_type').val(response.data.problem_type);
				$('#problem_message').val(response.data.problem_message);
				$('#modal_problem_form').modal('show');
			}else{
				console.log(response);
			}
		},
		error: function(error){
			console.log(error);
		}
	});
}


function delete_problems(id){
	swal({
		title: "Are you sure?",
		text: "Do you want to delete problems?",
		type: "warning",
		showCancelButton: true,
		confirmButtonColor: "#DD6B55",
		confirmButtonText: "Yes",
		closeOnConfirm: false
	},
	function(){
		$.ajax({
			type:"DELETE",
			url:"{{ route('problems.delete') }}/"+id,
			data:{},
			dataType:'json',
			beforeSend:function(){
		},
		success:function(response){
			// console.log(response);
			if (response.status == true) {
				show_problems();
				swal("Success", response.message, "success");
			}else{
				console.log(response);
			}
		},
		error: function(error){
			console.log(error);
		}
		});
	});
}

</script>
@endsection