routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\UserAccountController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\ProblemController;
use App\Http\Controllers\StudentProfileController;
use App\Http\Controllers\ProblemDashboardController;
use App\Http\Controllers\CouncelingController;
use App\Http\Controllers\NewsAndUpdateController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\AccountForumController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [UserController::class, 'landing'])->name('home');


Route::get('/login', function () {
    return view('Auth.index');
})->name('login');

Route::get('/activities', function () {
    return view('Landing.activities');
})->name('activities');

Route::get('/visionMission', function () {
    return view('Landing.visionMission');
})->name('visionMission');

Route::get('/newsupdates', function () {
    return view('Landing.newsupdates');
})->name('newsupdates');

Route::get('/strands', function () {
    return view('Landing.strands');
})->name('strands');

Route::get('/Organization', function () {
    return view('Landing.Organization');
})->name('Organization');

Route::get('/aboutus', function () {
    return view('Landing.aboutus');
})->name('aboutus');

Route::get('/registration', function () {
    return view('Auth.register');
})->name('registration');


Route::get('/forget-password', function () {
    return view('Auth.forgetPassword');
})->name('forget_password');

//sample for reset password
Route::get('/reset-password/{user_id?}', function () {
    return view('Auth.ResetPassword');
})->name('reset-password');

//Authentications/Login
Route::group(['prefix'=> 'auth', 'as' => 'auth.'], function(){
	// For Login
	Route::controller(AuthController::class)->group(function () {
 		 Route::post('request', 'authenticate')->name('authenticate');
 		 Route::get('forget-password-send', 'forgetPassword')->name('forget_password_send');
 		 Route::post('reset-password-send', 'resetPassword')->name('reset_password_send');
	});
});


Route::controller(UserController::class)->group(function(){
	Route::group(['prefix'=> 'users', 'as' => 'users.'], function(){
		 Route::get('', 'index')->name('index');
		 Route::get('list', 'list')->name('list');
		 Route::get('find/{user_id}', 'find')->name('find');
		 Route::post('add', 'add')->name('add');
		 Route::delete('delete/{user_id}', 'trash')->name('delete');
	});
});

Route::group(['middleware' => ['auth']], function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    // staff management
    Route::controller(StaffController::class)->group(function(){
		Route::group(['prefix'=> 'students', 'as' => 'students.'], function(){
			 Route::get('', 'index')->name('index');
			 Route::get('list', 'list')->name('list');
			 Route::get('find/{student_id?}', 'find')->name('find');
			 Route::post('add', 'add')->name('add');
			 Route::delete('delete/{student_id}', 'trash')->name('delete');
		});
	});


    //Students management
	Route::controller(UserAccountController::class)->group(function(){
		Route::group(['prefix'=> 'user_accounts', 'as' => 'user_accounts.'], function(){
			 Route::get('/students', 'index')->name('index');
			 Route::get('list', 'list')->name('list');
			 Route::get('find/{user_id}', 'find')->name('find');
			 Route::post('add', 'add')->name('add');
			 Route::delete('delete/{user_id}', 'trash')->name('delete');
			 Route::get('approve', 'approve')->name('approve');
			 Route::get('disapprove', 'disapprove')->name('disapprove');

		});
	});

	//staff management
	Route::controller(StaffController::class)->group(function(){
		Route::group(['prefix'=> 'staff', 'as' => 'staff.'], function(){
			 Route::get('/students', 'index')->name('index');
			 Route::get('list', 'list')->name('list');
			 Route::get('find/{user_id}', 'find')->name('find');
			 Route::post('add', 'add')->name('add');
			 Route::delete('delete/{user_id}', 'trash')->name('delete');
		});
	});

    Route::get('dashboard', [DashboardController::class, 'index'])->name('index');



});

Route::group(['as' => 'admin.', 'middleware' => ['auth']], function(){
    Route::get('dashboard', [DashboardController::class, 'index'])->name('index');
});


Route::group(['prefix'=> 'account', 'as' => 'account.',  'middleware' => ['auth']], function(){
    Route::get('', [AccountController::class, 'index'])->name('index');
    Route::get('find/{id?}', [AccountController::class, 'find'])->name('find');
    Route::get('edit', [AccountController::class, 'edit'])->name('edit');
});

//problem
Route::group(['prefix' => 'problems', 'as' => 'problems.'], function(){
	Route::controller(ProblemController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::delete('delete/{id?}', 'delete')->name('delete');
	});
});


Route::group(['prefix'=> 'student-profile', 'as' => 'student-profile.',  'middleware' => ['auth']], function(){
    Route::get('', [StudentProfileController::class, 'index'])->name('index');
    Route::get('/change-password', [StudentProfileController::class, 'changePassword'])->name('changePassword');
    Route::get('/change', [StudentProfileController::class, 'change'])->name('change');
    Route::post('/upload', [StudentProfileController::class, 'upload'])->name('upload');
   
});



Route::group(['prefix'=> 'counseling', 'as' => 'counseling.',  'middleware' => ['auth']], function(){
    Route::get('{id?}', [CouncelingController::class, 'index'])->name('index');
});

Route::controller(ProblemDashboardController::class)->group(function(){
	Route::group(['prefix'=> 'problem-dashboard', 'as' => 'problem-dashboard.'], function(){
		 Route::get('', 'index')->name('index');
		 Route::get('active', 'active')->name('active');
		 Route::get('list-active', 'listActive')->name('list_active');
		 Route::get('list', 'list')->name('list');
		 Route::get('find/{id}', 'find')->name('find');
		 Route::post('add', 'add')->name('add');
		 Route::delete('delete/{id}', 'trash')->name('delete');
		 Route::get('approve', 'approve')->name('approve');
		 Route::get('disapprove', 'disapprove')->name('disapprove');
		 Route::get('seen', 'seen')->name('seen');
		 Route::get('list-solve', 'listSolve')->name('list_solve');
		 Route::get('solve', 'solve')->name('solve');
	});
});


Route::controller(NewsAndUpdateController::class)->group(function(){
	Route::group(['prefix'=> 'news_and_update', 'as' => 'news_and_update.'], function(){
		 Route::get('', 'index')->name('index');
    	 Route::get('/activities', [NewsAndUpdateController::class, 'activities'])->name('activities');
    	 Route::get('/news', [NewsAndUpdateController::class, 'news'])->name('news');
	});
});

Route::controller(ForumController::class)->group(function(){
	Route::group(['prefix'=> 'forum', 'as' => 'forum.'], function(){
		 Route::get('/{id?}', 'index')->name('index');
	});
});

Route::get('send', [ForumController::class, 'send'])->name('message.send');
Route::get('list', [ForumController::class, 'list'])->name('forum.list');


Route::controller(AccountForumController::class)->group(function(){
	Route::group(['prefix'=> 'account-forum', 'as' => 'account-forum.'], function(){
		 Route::get('/{id?}', 'index')->name('index');
	});
});

Route::get('account-send', [AccountForumController::class, 'send'])->name('accountMessage.send');
Route::get('account-list', [AccountForumController::class, 'list'])->name('accountForum.list');
Route::get('account-solve', [AccountForumController::class, 'solve'])->name('accountForum.solve');


Route::controller(InboxController::class)->group(function(){
	Route::group(['prefix'=> 'account-inbox', 'as' => 'account-inbox.'], function(){
		 Route::get('', 'index')->name('index');
		 Route::get('/seen-user/{id?}', 'seenUser')->name('seen');
    	
	});
});

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Problem;
use App\Models\Forum;
use Validator;
use Auth;

class AccountController extends Controller
{
    public function index(){
        $inbox  = Problem::where('user_id', Auth::user()->user_id)->where('status', '!=', '2')->where('status', '!=', '0')->count();
        $pending = Problem::where('user_id', Auth::user()->user_id)->where('status', 0)->count();
        $active = Problem::where('user_id', Auth::user()->user_id)->where('status', 1)->count();
        $solve = Problem::where('user_id', Auth::user()->user_id)->where('status', 3)->count();
        $students = User::whereNull('deleted_at')->where('user_type', 3)->count();
        $staff = User::where('user_id', Auth::user()->user_id)->whereNull('deleted_at')->where('user_type', 2)->count();
        return view('AccountDashboard.index', compact('pending', 'active', 'students', 'staff', 'solve', 'inbox'));
    }

    public function find($id){
    	$users = User::where('user_Id', $id)->first();
    	return response()->json(['status' => true, 'data' => $users]);
    }

    public function edit(Request $request){
    	$first_name = $request->get('first_name');
        $middle_name = $request->get('middle_name');
        $last_name = $request->get('last_name');
        $gender = $request->get('gender');
        $contact = $request->get('contact');
        $province = $request->get('province');
        $city = $request->get('city');
        $address = $request->get('address');
        $email = $request->get('email');
        $password = $request->get('password');
        $student_no = $request->get('student_no');
        $strand = $request->get('strand');

      	$validator = Validator::make($request->all(),[
      		'first_name' => 'required',
            'last_name' => 'required',
            'gender' => 'required',
            'section' => 'required',
            'province' => 'required',
            'city' => 'required',
            'barangay' => 'required',
            'address' => 'required',
            'email' => 'required|email',
            'student_no' => 'min:10|max:12|required',
            'strand' => 'required',
      	]);
      	if ($validator->fails()) {
      		return response()->json(['status' => false, 'error' => $validator->errors()]);
      	}else{
      		$users = User::where('user_id', Auth::user()->user_id)->first();
      			$users->first_name = $first_name;
                $users->middle_name = $middle_name;
                $users->last_name = $last_name;
                $users->gender = $gender;
                $users->contact = $contact;
                $users->province = $province;
                $users->city = $city;
                $users->address = $address;
                $users->email = $email;
                $users->student_no = $student_no;
                $users->strand = $strand;
                $users->password = $password;
                $users->barangay = $request->get('barangay');
                $users->guardian_name = $request->get('guardian_name');
                $users->section = $request->get('section');
                if($users->save()){
                    return response()->json(['status' => true, 'message' => 'Users updated successfully!']);
                }
      	}
    }
}

resources/views/Layout/account/app.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>@yield('title')</title>
		@include('Layout.header')
		@yield('css')
	</head>
	<body class="hold-transition sidebar-mini layout-fixed">
		<div class="wrapper">
			@include('Layout.account.nav')
			@include('Layout.account.sidebar')
		 	@yield('breadcrumbs')
		 	<div class="content-wrapper">
		 		<section class="content">
					 <div class="container-fluid">
							@yield('content')
					</div>
				 </section>
		 	</div>
		</div>
	</body>
	@include('Layout.footer')
	@yield('script')
</html>

resources/views/Layout/account/nav.blade.php
<nav class="main-header navbar navbar-expand-lg bg-dark navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
         <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item">
         <a class="nav-link" href="{{ route('home') }}">News and Updates</a>
      </li>
    </ul>

    <!-- <ul class="navbar-nav ml-auto pr-2">
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          @if(count_all_notifs() == 0)
          @else
          <span class="badge badge-warning navbar-badge">{{count_all_notifs()}}</span>
          @endif
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">{{count_all_notifs()}} Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item text-primary">
            <i class="nav-icon fas fa-hands-helping"></i> {{notif_problem()}} new counseling
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item text-primary">
           <i class="fas fa-envelope mr-2"></i> unread message
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item text-primary">
             <i class="fas fa-users mr-2"></i> {{new_students()}} pending students
          </a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    </ul> -->

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
         <a  href="{{ route('logout') }}" class="btn btn-outline-secondary my-2 my-sm-0 text-light">Logout</a>
      </li>
    </ul>
  </div>
</nav>

<!--  -->

resources/views/Layout/account/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-dark bg-dark elevation-4">
  <!-- Brand Logo -->
   <a class="brand-link" style="border-color: #a4b0d6;">
      <img src="{{ asset('img/logo.png') }}" alt="Miakata Logo" class="brand-image" >
      <span class="brand-text font-weight-light">ASHS</span>
    </a>
  <div class="sidebar p-0 mt-2">
    <nav class="sidebar side-item">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item ml-4 mt-1">
            <p class="text-primary text-lg"> 
              <i class="fa-sharp fa-solid fa-user"> </i>
              {{' '.Auth::user()->first_name.' '.Auth::user()->last_name}}
            </p>
        </li>
        <!-- <li class="nav-item ">
          <a href="{{ route('account.index') }}" class="nav-link">
            <i class="fas fa-tachometer-alt"></i> 
            <p>
              Dashboard
            </p>
          </a>
        </li> -->
        <li class="nav-item ">
          <a href="{{ route('problems.index')}}" class="nav-link">
            <i class="fas fa-sms"></i>
            <p>
              Counselling
            </p>
          </a>
        </li>
        <li class="nav-item ">
          <a href="{{ route('account-inbox.index') }}" class="nav-link">
            <i class="fas fa-inbox"></i>
            <p>
              Inbox
            </p>
          </a>
        </li>
        <li class="nav-item ">
          <a href="{{ route('student-profile.index')}}" class="nav-link">
            <i class="fas fa-user-cog"></i>
            <p>
              Profile Settings
            </p>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</aside>